

export default function Head() {
  return (
    <>
      <title>Next.js | State</title>
      <meta name="description" content="Generated by create next.js app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}